export const GET_ALL_SHELF_PRODUCTS = 'GET_SHELF_PRODUCTS';
export const GET_ALL_PALLENT_PRODUCTS = 'GET_PALLENT_PRODUCTS';
export const GET_ALL_FLOOR_PRODUCTS = 'GET_FLOOR_PRODUCTS';
export const GET_PRODUCT_REPORT = 'GET_PRODUCT_REPORT';
export const GET_PRODUCT_NEAR_TO_EXPIRE = 'GET_PRODUCT_NEAR_TO_EXPIRE';
export const GET_PRODUCT_BY_BARCODE = 'GET_BARCODE_PRODUCT';
