export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USER_CHECKIN = 'GET_ALL_USER_CHECKIN';
export const GET_CUSTOMER_INVOICE = 'GET_CUSTOMER_INVOICE';
